### ISSUE TITLE
v2 release logistics checklist

### ISSUE THREAD

**Issue by chrisjkuch** [drivendataorg/cookiecutter-data-science#346]
- [x] Manually publish to PyPI
- [x] Redirect GH Pages site to Render site
  - [x] HTML redirect page
  - [x] Disable GH Pages on repo

See also #315
